### ISSUE TITLE
Action doesn't fail when it actually should

### ISSUE THREAD

**Issue by WieFel** [deepakputhraya/action-branch-name#19]
I have the following step:
```yaml
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/([a-z\-\/])+' # Regex the branch should match. This example enforces grouping
          ignore: master,main,dev # Ignore exactly matching branch names from convention
```
My branch naming convention is that it should consist only of lowercase letters, slashes or minus signs. I.e. `feature/my-new-feature` would be a valid name, while with `feature/myNewFeature` it should throw an error.

If I put this regex into [regex101.com](https://regex101.com/), and add the test string, it doesn't match the whole string, which would be expected and which should make the action fail (!?)
<img width="270" alt="image" src="https://github.com/deepakputhraya/action-branch-name/assets/8345062/13b03d8d-e577-4d50-9127-2d451ea0117b">

But with exactly this example as a branch name, the action succeeds, also if it shouldn't.
